name: 'server_shelf'
version: 0.0.1
description: A minimal web server using the shelf package.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.10.0 <0.14.0'
  shelf: "^0.6.4+1"
  shelf_static: "^0.2.3+1"
