name: 'server_shelf'
version: 0.0.1
description: A minimal web server using the shelf package.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  redstone: 0.6.1
  redstone_mapper: "^0.2.0-beta.1+1"
  redstone_mapper_mongo: "^0.2.0-beta.1"
